apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: platform-argocd
spec:
  description: "Core Platform Infrastructure (Istio, Namespaces)"

  sourceRepos:
    - "*"

  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: "platform-*"
      server: https://kubernetes.default.svc
    - namespace: "apps-*"
      server: https://kubernetes.default.svc # manages namespaces
    - namespace: "data-*"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*" # platform needs elevated privileges
