apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: platform-argocd
spec:
  description: "Core Platform Infrastructure (Istio, Namespaces, CRDs)"
  sourceRepos:
    - "https://github.com/your-org/ecommerce-platform.git"
  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: "platform-*"
      server: https://kubernetes.default.svc
    - namespace: "apps-*"
      server: https://kubernetes.default.svc
    - namespace: "data-*"
      server: https://kubernetes.default.svc
    - namespace: "tooling-*"
      server: https://kubernetes.default.svc
    - namespace: "sonarqube"
      server: https://kubernetes.default.svc
    - namespace: "kafka"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
