apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tooling
  namespace: platform-argocd
spec:
  description: "Ops Tooling (Airflow, Sonar, Spark)"
  sourceRepos:
    - "https://github.com/your-org/ecommerce-platform.git"
  destinations:
    - namespace: sonarqube
      server: https://kubernetes.default.svc
    - namespace: apps-async
      server: https://kubernetes.default.svc
    - namespace: tooling-airflow
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
