steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - DOCKER_BUILDKIT=1
    args:
      - '-c'
      - |
        set -e
        echo "Detecting all microservices..."

        for SERVICE in $$(find services -mindepth 1 -maxdepth 1 -type d -exec basename {} \;); do

          # Skip shared-lib AND go.work (or any other non-service dirs)
          if [[ "$$SERVICE" == "shared-lib" || "$$SERVICE" == "go.work" ]]; then
            echo "Skipping $$SERVICE"
            continue
          fi

          IMAGE="us-central1-docker.pkg.dev/ecommerce-microservice-53/ecommerce-repo/$${SERVICE}:latest"

          echo "========================================="
          echo "Building and pushing to GCP: $$SERVICE"
          echo "========================================="

          if [[ "$${SERVICE}" == "storefront-web" ]]; then
            docker build \
              -t $${IMAGE} \
              -f services/storefront-web/Dockerfile services/storefront-web/
          else
            docker build \
              --build-arg SERVICE_NAME=$${SERVICE} \
              -t $${IMAGE} \
              -f Dockerfile.services .
          fi


          docker push $${IMAGE}

        done

        echo "All microservices built and pushed successfully."
