# =========================
# POSTGRES CREDS
# (expects JSON secret in GCP with multiple keys)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: data-postgres

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: postgres-creds
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: postgres-creds

---
# =========================
# REDIS CREDS
# (expects JSON secret in GCP)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: data-redis

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: redis-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: redis-secret

---
# =========================
# KAFKA CREDS
# (single value secret → use data.secretKey instead)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-creds
  namespace: kafka

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: kafka-secret
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: kafka-password

---
# =========================
# AIRFLOW CREDS
# (single value secret)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-creds
  namespace: tooling-airflow

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: airflow-metadata-secret
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: airflow-db-password

---
# =========================
# METABASE CREDS
# (single value secret)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-creds
  namespace: tooling-metabase

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: metabase-db-secret
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: metabase-db-password

---
# =========================
# AUTH SERVICE CREDS
# (structured JSON secret in GCP)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-db
  namespace: apps-core

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: auth-service-secrets
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: auth-service-db


---
# =========================
# CONVERSION WEBHOOK CREDS
# (structured JSON secret in GCP)
# =========================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conversion-webhook
  namespace: apps-async

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: conversion-webhook-secrets
    creationPolicy: Owner

  data:
    - secretKey: clickbank-secret-key
      remoteRef:
        key: conversion-webhook



