apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: data-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
  data:
    # Postgres superuser
    - secretKey: postgres-password
      remoteRef:
        key: postgres-app-password

    # Application user
    - secretKey: password
      remoteRef:
        key: postgres-app-password

    # REQUIRED for replication mode
    - secretKey: replication-password
      remoteRef:
        key: postgres-replication-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: data-redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-auth-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-creds
  namespace: kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kafka-sasl-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-creds
  namespace: tooling-airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: airflow-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: airflow-metadata-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metabase-creds
  namespace: tooling-metabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: metabase-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: metabase-db-password
