apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: data-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres-creds
    - secretKey: password
      remoteRef:
        key: postgres-creds
    - secretKey: replication-password
      remoteRef:
        key: postgres-creds
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: data-redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-creds
  namespace: kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: kafka-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kafka-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-creds
  namespace: tooling-airflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: airflow-metadata-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: airflow-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-creds
  namespace: tooling-metabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: metabase-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: metabase-db-password
