apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conversion-webhook
  namespace: apps-async
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: conversion-webhook-secrets
    creationPolicy: Owner
  data:
    - secretKey: clickbank-secret-key
      remoteRef:
        key: conversion-webhook
