apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: data-postgres

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: postgres-creds
    creationPolicy: Owner

  data:

  - secretKey: postgres-password
    remoteRef:
      key: postgres-creds
      property: postgres-password

  - secretKey: password
    remoteRef:
      key: postgres-creds
      property: password

  - secretKey: replication-password
    remoteRef:
      key: postgres-creds
      property: replication-password
