# infra/scaling/hpa-pdb-template.yaml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dynamic-microservice-hpa
  namespace: apps-core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: YOUR_SERVICE_NAME
  minReplicas: 3
  maxReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: strict-pdb
  namespace: apps-core
spec:
  # Guarantees high availability during GKE Node Upgrades or Preemptions
  maxUnavailable: 1
  selector:
    matchLabels:
      app: YOUR_SERVICE_NAME
