apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: postgres-creds
    creationPolicy: Owner
    template:
      data:
        username: postgres
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: postgres-creds
