# infra/spark/spark-submit.yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: funnel-analysis
  namespace: analytics
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.1.1" # Custom image with JDBC/GCS libs in real scenario
  mainApplicationFile: "local:///opt/spark/jobs/funnel_analysis.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    serviceAccount: spark-sa
  executor:
    cores: 1
    instances: 2
    memory: "512m"
  deps:
    pyFiles: []
    jars:
      - "local:///opt/spark/jars/postgresql-42.2.18.jar"
      - "local:///opt/spark/jars/gcs-connector-hadoop2-2.2.0.jar"
