apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: funnel-analysis
  namespace: data
spec:
  type: Python
  mode: cluster
  sparkVersion: "3.4.1"
  image: docker.io/apache/spark:3.4.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/jobs/funnel_analysis.py
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
  volumes:
    - name: spark-jobs
      configMap:
        name: spark-jobs
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    serviceAccount: spark-sa
    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs
    env:
      - name: DB_URL
        value: jdbc:postgresql://postgres-primary.data-postgres.svc.cluster.local:5432/ecommerce_db
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: password
  executor:
    cores: 1
    instances: 2
    memory: "1024m"
    volumeMounts:
      - name: spark-jobs
        mountPath: /opt/spark/jobs
    env:
      - name: DB_URL
        value: jdbc:postgresql://postgres-primary.data-postgres.svc.cluster.local:5432/ecommerce_db
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: password
  deps:
    packages:
      - org.postgresql:postgresql:42.6.0
