apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: {{ .Release.Namespace }}
