# infra/kafka/kafka-brokers.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9093
          name: controller
        command:
          - "bash"
          - "-c"
          - |
            # Extract ordinal index from hostname (kafka-0 -> 0)
            export KAFKA_NODE_ID=${HOSTNAME##*-}
            export KAFKA_PROCESS_ROLES=controller,broker
            export KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            # Advertised listener needs to be reachable by other pods and potentially outside
            # Using pod FQDN: kafka-0.kafka-headless.kafka.svc.cluster.local
            export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOSTNAME}.kafka-headless.kafka.svc.cluster.local:9092
            
            export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            export KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            export KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            
            # Quorum voters: 0@kafka-0.kafka-headless.kafka.svc.cluster.local:9093
            # Assuming 1 replica named kafka-0
            export KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0.kafka-headless.kafka.svc.cluster.local:9093
            
            # Storage
            export KAFKA_LOG_DIRS=/var/lib/kafka/data
            
            # Update the configuration file to point to the correct log directory
            # This is required because kafka-storage.sh format doesn't accept overrides via CLI commonly
            echo "Updating log.dirs in server.properties..."
            sed -i "s|log.dirs=.*|log.dirs=$KAFKA_LOG_DIRS|" /opt/kafka/config/kraft/server.properties

            # Format storage if not exists (Apache image specific, checking if meta.properties exists)
            if [ ! -f /var/lib/kafka/data/meta.properties ]; then
              echo "Formatting storage..."
              # Critical: All brokers must use the SAME Cluster ID to form a quorum.
              CLUSTER_ID="MkU3OEVBNTcwNTJENDM2Qk"
              /opt/kafka/bin/kafka-storage.sh format -t $CLUSTER_ID -c /opt/kafka/config/kraft/server.properties
            fi
            
            # Start Kafka
            /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties \
              --override node.id=$KAFKA_NODE_ID \
              --override process.roles=$KAFKA_PROCESS_ROLES \
              --override listeners=$KAFKA_LISTENERS \
              --override advertised.listeners=$KAFKA_ADVERTISED_LISTENERS \
              --override listener.security.protocol.map=$KAFKA_LISTENER_SECURITY_PROTOCOL_MAP \
              --override controller.listener.names=$KAFKA_CONTROLLER_LISTENER_NAMES \
              --override inter.broker.listener.name=$KAFKA_INTER_BROKER_LISTENER_NAME \
              --override controller.quorum.voters=$KAFKA_CONTROLLER_QUORUM_VOTERS \
              --override log.dirs=$KAFKA_LOG_DIRS
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 100Gi
