# infra/kafka/kafka-topics.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-script
  namespace: kafka
data:
  create-topics.sh: |
    #!/bin/bash
    set -e
    
    # Wait for Kafka to be ready
    until /opt/kafka/bin/kafka-topics.sh \
      --bootstrap-server kafka-bootstrap.kafka.svc.cluster.local:9092 \
      --list >/dev/null 2>&1; do
      echo "Waiting for Kafka to be ready..."
      sleep 5
    done
    
    BOOTSTRAP_SERVER="kafka-bootstrap.kafka.svc.cluster.local:9092"
    
    # Topics list
    topics=("page.viewed" "cta.clicked" "campaign.attributed" "checkout.redirected" "conversion.completed" "user.signup" "checkout.completed")
    
    # Create topics
    for topic in "${topics[@]}"; do
      echo "Creating topic: $topic"
      # RF=3 for 3 brokers (Production/Cloud standard for high availability)
      # Partitions=6 (Good concurrency start)
      /opt/kafka/bin/kafka-topics.sh --create --if-not-exists \
        --bootstrap-server $BOOTSTRAP_SERVER \
        --partitions 6 \
        --replication-factor 3 \
        --config retention.ms=604800000 \
        --topic "$topic"
    done
    
    echo "All topics created."
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: topic-creator
        image: apache/kafka:3.7.0
        command: ["/bin/bash", "/scripts/create-topics.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: kafka-topics-script
          defaultMode: 0755
      restartPolicy: OnFailure
