# infra/kafka/kafka.yaml

# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
# 2. Secret for Cluster ID (KRaft)
apiVersion: v1
kind: Secret
metadata:
  name: kafka-cluster-id
  namespace: kafka
type: Opaque
stringData:
  # Random UUID or consistent ID for the cluster
  cluster-id: "MkU3OEVBNTcwNTJENDM2Qk"
---
# 3. Headless Service (Internal Discovery)
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: plaintext
    targetPort: 9092
  - port: 9093
    name: controller
    targetPort: 9093
  clusterIP: None
  selector:
    app: kafka
---
# 4. Client Service (Bootstrap)
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    name: plaintext
    targetPort: 9092
  selector:
    app: kafka
---
# 5. Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
  namespace: kafka
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kafka
---
# 6. StatefulSet (KRaft Mode)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308" # Assuming JMX exporter or internal metrics
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9093
          name: controller
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms1G"
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: kafka-cluster-id
              key: cluster-id
        command:
        - "bash"
        - "-c"
        - |
          # 1. Identity & Network Config
          # Hostname is kafka-0, kafka-1, etc.
          NODE_ID=${HOSTNAME##*-}
          export KAFKA_NODE_ID=$NODE_ID
          
          # Roles: All nodes are brokers and controllers in this 3-node setup
          export KAFKA_PROCESS_ROLES=controller,broker
          
          # Listeners
          # PLAINTEXT:9092 (Internal/Clients), CONTROLLER:9093 (Inter-broker/raft)
          export KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
          
          # Advertised Listeners (reachable from other pods)
          # kafka-0.kafka-headless.kafka.svc.cluster.local
          export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOSTNAME}.kafka-headless.kafka.svc.cluster.local:9092
          
          export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          export KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
          export KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          
          # Quorum Voters (static list for 3 nodes)
          # Format: id@host:port
          export KAFKA_CONTROLLER_QUORUM_VOTERS="0@kafka-0.kafka-headless.kafka.svc.cluster.local:9093,1@kafka-1.kafka-headless.kafka.svc.cluster.local:9093,2@kafka-2.kafka-headless.kafka.svc.cluster.local:9093"
          
          export KAFKA_LOG_DIRS=/var/lib/kafka/data
          
          # 2. KRaft Formatting
          if [ ! -f /var/lib/kafka/data/meta.properties ]; then
            echo "Formatting storage with Cluster ID: $CLUSTER_ID"
            /opt/kafka/bin/kafka-storage.sh format -t $CLUSTER_ID -c /opt/kafka/config/kraft/server.properties
          else
            echo "Storage already formatted."
          fi
          
          # 3. Start Kafka
          echo "Starting Kafka Node $NODE_ID..."
          exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties \
            --override node.id=$KAFKA_NODE_ID \
            --override process.roles=$KAFKA_PROCESS_ROLES \
            --override listeners=$KAFKA_LISTENERS \
            --override advertised.listeners=$KAFKA_ADVERTISED_LISTENERS \
            --override listener.security.protocol.map=$KAFKA_LISTENER_SECURITY_PROTOCOL_MAP \
            --override controller.listener.names=$KAFKA_CONTROLLER_LISTENER_NAMES \
            --override inter.broker.listener.name=$KAFKA_INTER_BROKER_LISTENER_NAME \
            --override controller.quorum.voters=$KAFKA_CONTROLLER_QUORUM_VOTERS \
            --override log.dirs=$KAFKA_LOG_DIRS
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: kafka-fast-storage
      resources:
        requests:
          storage: 10Gi
