apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-monitor
  namespace: platform-observability
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http
      path: /probe
      interval: 30s
      scrapeTimeout: 30s
      params:
        module: [http_2xx]
      metricRelabelings:
        - sourceLabels: [instance]
          targetLabel: target
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __param_target
          sourceLabels: [__address__]
        - targetLabel: __address__
          replacement: blackbox-exporter.platform-observability.svc.cluster.local:9115
  jobLabel: blackbox
  selector:
    matchLabels:
      app: blackbox-exporter
  namespaceSelector:
    matchNames:
      - platform-observability
