apiVersion: v2
name: external-secrets-wrapper
description: External Secrets Operator wrapper
type: application
version: 1.0.0

dependencies:
  - name: external-secrets
    version: 0.9.13
    repository: https://charts.external-secrets.io
