apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: ecommerce-microservice-53
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
