apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-databases
  namespace: platform-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: data
  source:
    repoURL: https://github.com/your-org/ecommerce-platform.git
    targetRevision: HEAD
    path: infra/databases
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-postgres # Default, though charts specify their own
  syncPolicy:
    automated:
      prune: false # DANGEROUS for data
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-kafka
  namespace: platform-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: data
  source:
    repoURL: https://github.com/your-org/ecommerce-platform.git
    targetRevision: HEAD
    path: infra/kafka
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-kafka
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
