apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-databases
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: data
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/databases
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-postgres
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-kafka
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: data
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/kafka
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: data-kafka
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-kafka-topics
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: data
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: resources/kafka-topics
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
