apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infra
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Manifests specify metadata.namespace
  syncPolicy:
    automated:
      prune: false # Safety: Don't auto-delete namespaces if removed from git immediately
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-istio
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/istio
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
