apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling-sonarqube
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/sonarqube
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling-spark
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/spark
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-async
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tooling-airflow
  namespace: platform-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    repoURL: https://github.com/Moiz-Ali-Moomin/microservice-ecommerce-gcp-cloud-gke-setup
    targetRevision: HEAD
    path: infra/airflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling-airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
