apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: platform-observability
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP
