# infra/gke/nodepools.yaml
# GKE Node Pools managed via Config Connector

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: general-pool
  namespace: config-control
spec:
  clusterRef:
    name: ecommerce-platform-prod

  location: us-central1

  management:
    autoRepair: true
    autoUpgrade: true

  autoscaling:
    minNodeCount: 1
    maxNodeCount: 5

  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0

  nodeConfig:
    machineType: e2-standard-4
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD

    serviceAccountRef:
      name: gke-nodes-sa

    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform

    workloadMetadataConfig:
      mode: GKE_METADATA

    shieldedInstanceConfig:
      enableSecureBoot: true
      enableIntegrityMonitoring: true

    labels:
      env: prod
      team: platform
      pool: general

    tags:
      - gke-general

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: analytics-pool
  namespace: config-control
spec:
  clusterRef:
    name: ecommerce-platform-prod

  location: us-central1

  management:
    autoRepair: true
    autoUpgrade: true

  autoscaling:
    minNodeCount: 0
    maxNodeCount: 3

  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0

  nodeConfig:
    machineType: n2-highmem-8
    diskSizeGb: 200
    diskType: pd-ssd
    imageType: COS_CONTAINERD

    # 💸 Cost-optimized for batch / Spark
    spot: true

    serviceAccountRef:
      name: gke-nodes-sa

    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform

    taints:
      - key: workload
        value: analytics
        effect: NO_SCHEDULE

    workloadMetadataConfig:
      mode: GKE_METADATA

    shieldedInstanceConfig:
      enableSecureBoot: true
      enableIntegrityMonitoring: true

    labels:
      team: data
      workload: analytics
      pool: analytics

    tags:
      - gke-analytics
